# Generated by Django 5.2.10 on 2026-02-06 03:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address (used for login)",
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="User's phone number in Nigerian format",
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+2348012345678' or '08012345678'",
                                regex="^\\+?234?\\d{10,13}$",
                            )
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User's first name", max_length=150),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User's last name", max_length=150),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site.",
                    ),
                ),
                (
                    "is_merchant",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Designates whether the user is a merchant",
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Designates whether the user is an agent",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has verified their email address",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has verified their phone number",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when email was verified",
                        null=True,
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when phone was verified",
                        null=True,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the user joined",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, help_text="Last login timestamp", null=True
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="User's profile image",
                        null=True,
                        upload_to="profile_images/",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "last_login_device",
                    models.CharField(
                        blank=True,
                        help_text="Device information of last login",
                        max_length=255,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email Verification"),
                            ("PHONE", "Phone Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                        ],
                        help_text="Type of OTP verification",
                        max_length=20,
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(help_text="6-digit OTP code", max_length=6),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this OTP has been used"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When this OTP expires")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this OTP belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active"], name="accounts_us_email_f69303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number", "is_active"],
                name="accounts_us_phone_n_45a1ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_merchant", "is_active"],
                name="accounts_us_is_merc_310c12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_agent", "is_active"], name="accounts_us_is_agen_ddd2f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["user", "otp_type", "is_used"],
                name="accounts_ot_user_id_949a16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["otp_code", "expires_at"], name="accounts_ot_otp_cod_3be8cb_idx"
            ),
        ),
    ]
