# Generated by Django 5.2.10 on 2026-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="transfer_pin",
            field=models.CharField(
                blank=True,
                help_text="Hashed 4-digit transfer PIN",
                max_length=128,
                null=True,
            ),
        ),
    ]
