# Generated by Django 5.2.10 on 2026-02-07 02:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was deleted",
                        null=True,
                    ),
                ),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (0, "Unverified"),
                            (1, "Basic KYC"),
                            (2, "Intermediate KYC"),
                            (3, "Full KYC"),
                        ],
                        db_index=True,
                        default=0,
                        help_text="Current KYC verification tier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current verification status",
                        max_length=20,
                    ),
                ),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="Bank Verification Number (11 digits)",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="BVN must be exactly 11 digits",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True,
                        help_text="National Identification Number (11 digits)",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIN must be exactly 11 digits",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Residential address"),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state",
                    models.CharField(blank=True, help_text="State", max_length=100),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NIN", "National ID Card"),
                            ("DRIVERS_LICENSE", "Driver's License"),
                            ("VOTERS_CARD", "Voter's Card"),
                            ("INTERNATIONAL_PASSPORT", "International Passport"),
                        ],
                        help_text="Type of ID document",
                        max_length=50,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="ID document number", max_length=50
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded ID document (PDF or image)",
                        null=True,
                        upload_to="kyc/documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "selfie",
                    models.ImageField(
                        blank=True,
                        help_text="Selfie photo for verification",
                        null=True,
                        upload_to="kyc/selfies/%Y/%m/%d/",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When this KYC was verified", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if rejected)"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When KYC was first submitted", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this KYC verification expires (for periodic re-verification)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this KYC belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified this KYC",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Verification",
                "verbose_name_plural": "KYC Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was deleted",
                        null=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("UTILITY_BILL", "Utility Bill"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("EMPLOYMENT_LETTER", "Employment Letter"),
                            ("TAX_DOCUMENT", "Tax Document"),
                            ("BUSINESS_LICENSE", "Business License"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=50,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Uploaded document file",
                        upload_to="kyc/additional_documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this document"
                    ),
                ),
                (
                    "kyc",
                    models.ForeignKey(
                        help_text="Associated KYC record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_documents",
                        to="kyc.kyc",
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Document",
                "verbose_name_plural": "KYC Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kyc",
            index=models.Index(
                fields=["user", "status"], name="kyc_kyc_user_id_e1bb9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyc",
            index=models.Index(
                fields=["tier", "status"], name="kyc_kyc_tier_fff937_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyc",
            index=models.Index(
                fields=["status", "created_at"], name="kyc_kyc_status_b95802_idx"
            ),
        ),
    ]
