# Generated by Django 5.2.10 on 2026-02-08 05:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current wallet balance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "virtual_account_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique virtual account number for deposits",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether wallet is frozen (cannot send money)",
                    ),
                ),
                (
                    "freeze_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for freezing the wallet",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="wallets_user_id_9fb6cf_idx"),
                    models.Index(
                        fields=["virtual_account_number"],
                        name="wallets_virtual_8dd2db_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="wallets_created_61c0d8_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="wallet_balance_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("virtual_account_number__regex", "^\\d{10}$")
                        ),
                        name="virtual_account_10_digits",
                    ),
                ],
            },
        ),
    ]
