# Generated by Django 5.2.10 on 2026-02-06 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was deleted",
                        null=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique configuration key",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Configuration value (can be JSON string for complex data)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this configuration does",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was deleted",
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "iOS"), ("ANDROID", "Android")],
                        help_text="Platform for this version",
                        max_length=20,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Version number (e.g., 1.0.0)", max_length=20
                    ),
                ),
                ("build_number", models.IntegerField(help_text="Build number")),
                (
                    "minimum_supported_version",
                    models.CharField(
                        help_text="Minimum version that's still supported",
                        max_length=20,
                    ),
                ),
                (
                    "is_force_update",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users must update to this version",
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True, help_text="What's new in this version"
                    ),
                ),
                (
                    "download_url",
                    models.URLField(help_text="URL to download this version"),
                ),
            ],
            options={
                "verbose_name": "App Version",
                "verbose_name_plural": "App Versions",
                "ordering": ["-build_number"],
                "unique_together": {("platform", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was deleted",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("TRANSACTION", "Transaction"),
                            ("KYC_SUBMIT", "KYC Submission"),
                            ("KYC_APPROVE", "KYC Approval"),
                            ("KYC_REJECT", "KYC Rejection"),
                            ("WALLET_FREEZE", "Wallet Freeze"),
                            ("WALLET_UNFREEZE", "Wallet Unfreeze"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the model affected by this action",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the object affected",
                        max_length=255,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of changes made (field: {old: value, new: value})",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the action was performed",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string of the client"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about this action",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="core_auditl_user_id_5afea4_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="core_auditl_model_n_3fb686_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_auditl_action_29a2bf_idx",
                    ),
                ],
            },
        ),
    ]
